[winget]
1password = "AgileBits.1Password"
brave = "Brave.Brave"
calibre = "calibre.calibre"
ubuntu = "Canonical.Ubuntu"
git = "Git.Git"
ivpn = "IVPN.IVPN"
microsoft_appinstaller = "Microsoft.AppInstaller"
microsoft_edge = "Microsoft.Edge"
powershell = "Microsoft.PowerShell"
microsoft_ui_xaml_2_8 = "Microsoft.UI.Xaml.2.8"
microsoft_vclibs_desktop_14 = "Microsoft.VCLibs.Desktop.14"
microsoft_vcredist_2010_x64 = "Microsoft.VCRedist.2010.x64"
microsoft_vcredist_2010_x86 = "Microsoft.VCRedist.2010.x86"
microsoft_vcredist_2013_x64 = "Microsoft.VCRedist.2013.x64"
microsoft_vcredist_2013_x86 = "Microsoft.VCRedist.2013.x86"
microsoft_vcredist_2015_x64 = "Microsoft.VCRedist.2015+.x64"
microsoft_vcredist_2015_x86 = "Microsoft.VCRedist.2015+.x86"
visual_studio_code = "Microsoft.VisualStudioCode"
windows_terminal = "Microsoft.WindowsTerminal"
nvidia_physx = "Nvidia.PhysX"
obsidian = "Obsidian.Obsidian"
kalilinux = "OffSec.KaliLinux"
signal = "OpenWhisperSystems.Signal"
plexamp = "Plex.Plexamp"
qbittorrent = "qBittorrent.qBittorrent"
roonserver = "RoonLabs.RoonServer"
screenbox = "Starpine.Screenbox"
chezmoi = "twpayne.chezmoi"
steam = "Valve.Steam"
wand = "WeMod.WeMod"

[msstore]
9n6rqhpvl7pk = "9N6RQHPVL7PK"
xp89dcgq3k6vld = "XP89DCGQ3K6VLD"
